name: Integration Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install R2R
        run: |
          python -m pip install --upgrade pip
          pip install r2r

      - name: Start R2R server
        run: r2r serve --port=8000 &

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.x"

      - name: Install dependencies
        run: npm ci

      - name: Check if R2R server is running
        run: |
          sleep 10
          curl http://localhost:8000/health || echo "Server not responding"

      - name: Run integration tests
        run: npm run test
